### ISSUE TITLE
Isn't LayoutKit still using Auto Layout (NSAutoresizingMaskLayoutConstraint)?

### ISSUE THREAD

**Issue by Bartzy** [linkedin/LayoutKit#106]
Hi,

I hope this is the appropriate place to ask this type of questions.

I just wanted to ask, if any part of the view hierarchy is using Auto Layout, I think that UIKit "turns" Auto Layout on for every view, and setting frame/bounds/center for any view updates some `NSAutoresizingMaskLayoutConstraint` constraints.

Is this still the case with LayoutKit?
Is it still fast because these constraints are trivial and there's basically nothing to solve when they're used?

Thanks!

**Comment by nicksnyder** [comment]
All LayoutKit does is set frames on UIViews (x, y, width, height). Regardless of UIKit's implementation, there is really nothing left for UIKit to compute for the layout because it literally already has the answer that it needs (frames for all involved views).

Auto Layout may technically be involved, but the equations are trivially solved.

**Comment by Bartzy** [comment]
Thanks for the quick answer. LayoutKit seems awesome :)
