### ISSUE TITLE
ReloadableViewLayoutAdapter animatable CRUD operations

### ISSUE THREAD

**Issue by afrederick1** [linkedin/LayoutKit#15]
Hey guys, just started using the library today and have enjoyed working with it. I'm a little stuck and was hoping you could shed some light. I've got my layouts created using a UICollectionView with the `ReloadableViewLayoutAdapter`. The behavior I'm looking for is to load an initial dataset and render the layouts, then be able to insert, delete, move or update items using the collectionview animations. I can't find anything in the docs that describes animating data, and when I try to it winds up doing a reload instead. When the `update` function is called within the adapter the `incremental` value is always true, so it calls `reloadDataSync` on the collectionview instead of proceeding to call `insert`.

After doing the initial load how should I proceed to insert more items?

**Comment by nicksnyder** [comment]
As you have observed, `reload` is designed to reload the entire data set. The logic you are requesting is something that we would like to support, but hasn't been implemented yet (we punted on implementing it because we haven't had that use case yet).

To support what you are asking for we need to add methods `insert`, `update`, and `delete` with signatures similar to `reload` but with appropriate modifications.

@staguer This task was originally assigned to you; do you want to work on this?

**Comment by staguer** [comment]
This is indeed necessary and interesting functionality but it’s not in my list of tasks till August at the earliest. Avoiding race conditions in the async case should be fun. If anyone wants to take this up in the meantime, please feel free.

**Comment by nicksnyder** [comment]
@afrederick1 @staguer 

I am not sure if it makes more sense to provide an API that requires the full layout (much simpler code and API), or an API that only asks for the incremental layout changes (more complicated code and API). Implementing the latter is tricky due to how indexes are handled in batch updates.

Here is an example of the former:

```swift
/// Basically the same as `reload` except instead of calling `reloadData` it calls the appropriate methods to trigger animations
/// Note that layoutProvider produces the entire layout, not just the parts that changed.
public func performBatchUpdates(batchUpdates: BatchUpdates,
                                layoutProvider: Void -> T,
                                width: CGFloat? = nil,
                                height: CGFloat? = nil,
                                completion: ((Void) -> Void)? = nil) {
    // implementation
}

public struct BatchUpdates {
    public let insertItemsAtIndexPaths: [NSIndexPath]
    public let deleteItemsAtIndexPaths: [NSIndexPath]
    public let moveItemsAtIndexPaths: [IndexPathMove]

    public let insertSections: NSIndexSet
    public let deleteSections: NSIndexSet
    public let moveSections: [SectionMove]
}

public struct IndexPathMove {
    public let from: NSIndexPath
    public let to: NSIndexPath
}

public struct SectionMove {
    public let from: Int
    public let to: Int
}
```
