### ISSUE TITLE
What is the best way to update an existing view's property inside a hierarchy?

### ISSUE THREAD

**Issue by JayZhao** [linkedin/LayoutKit#156]
Sorry that I can't seem to find a better place to ask this question.

Say I have setup a complex UI hierarchy using LayoutKit and all the views have been created.
Now I want to update some of their properties. Like a button's `image`, `backgroundImage`, `text`, `font`, `isHidden`... 
Or, I want to hide a portion of the UI.

From what I've learned the only way to do this is to **rewrite the whole layout from root** even when updating a single child view's property if that property is related to it's frame. 

Any better way to build a **dynamic** layout?

**Comment by nicksnyder** [comment]
> Now I want to update some of their properties.

If you are updating a property that does not impact the view's size or position (e.g. color), then you can just capture a reference to the view in the configure block for the layout and update those properties at any point in the future.

> From what I've learned the only way to do this is to rewrite the whole layout from root even when updating a single child view's property if that property is related to it's frame.

Correct. The whole layout needs to be recomputed. The good news is that this is fast by design in LayoutKit. Auto Layout solves the same problem but it is generally slower (it also needs to resolve the constraint system any time a constraint changes).

The slow part is generally view creation and instantiation. To avoid this, you can assign each layout a `viewReuseId` and views that still exist in the new layout will get reused.

http://layoutkit.org/animations/

**Comment by JayZhao** [comment]
Thanks! I think this could be added to the "Get Started" section since it's a quite common question for people just coming from AutoLayout.
