### ISSUE TITLE
Opinion on combining with other library

### ISSUE THREAD

**Issue by alickbass** [linkedin/LayoutKit#161]
Hi guys! Thank you very much for you library! I really love it!

I have recently been working on this library called [ViewComponents](https://github.com/alickbass/ViewComponents) which helps to create immutable styles instead directly setting properties on views.

The thing that I left out of the scope of the library was the layout and the actual creation of the views. In my opinion, the `LayoutKit` is the perfect solution to fill this gap. They way I imagine the combination of these 2 libraries, is that `Layouts` apart from `config` block would also contain array of styles that could be applied to that view. 

Here is a sample code of the logic above:

```swift
let image = SizeLayout<UIImageView>(
    width: 80,
    height: 80,
    alignment: .center,
    styles:
    	.image(UIImage(named: imageName)),
    	.border(cornerRadius: 40, width: 3, color: .red),
    	.clipsToBounds(true)
)
```

The good thing here is that `ViewComponent` supports diffing and when the layout changes or some attributes change, it will only apply the diffs, which would be really hard to implement using config block.

I would really love to know what you think about this approach and if it is something interesting.

**Comment by nicksnyder** [comment]
> ViewComponent supports diffing

We created LayoutKit because we observed an actual performance problem with Auto Layout. I have yet to observe a performance problem caused by setting styles like what your library supports. Do you have evidence that the extra work you do diffing actually saves time elsewhere?

> helps to create immutable styles instead directly setting properties on views.

It seems like the main benefit of your library is being able to save styles separately from the views themselves. The problem of styling views is beyond the scope of LayoutKit, so consumers of LayoutKit are free to style view however they want.

> I imagine the combination of these 2 libraries

It seems like there is nothing preventing someone from using both of our libraries. I don't think there is any value in combining/coupling them though. It is better to have independent libraries that each solve a specific problem.

**Comment by alickbass** [comment]
@nicksnyder I agree with all your points! Thank you very much!
