### ISSUE TITLE
labellayout textAlignment is not work

### ISSUE THREAD

**Issue by 85636682** [linkedin/LayoutKit#31]
labellayout textAlignment is not work!
my code like this
```
let authorLayout = LabelLayout(
            text: author,
            font: UIFont.systemFontOfSize(20),
            config: { label in
                label.textAlignment = .Right
            }
        )
```

**Comment by nicksnyder** [comment]
A LabelLayout's default alignment is .topLeading so it will only use the width/height it needs for the content. Since the label will have exactly the width it needs, the textAlignment has no visual effect. It might help you understand if you put a background color on label for debugging.

One of these options is probably what you want:

```swift
let authorLayout = LabelLayout(
    text: author,
    font: UIFont.systemFontOfSize(20),
    alignment: .topFill,
    config: { label in
        label.backgroundColor = UIColor.redColor()
        label.textAlignment = .Right
    }
)
```
or
```swift
let authorLayout = LabelLayout(
    text: author,
    font: UIFont.systemFontOfSize(20),
    alignment: .topTrailing,
    config: { label in
        label.backgroundColor = UIColor.redColor()
    }
)
```

I am going to close this issue, but please reopen if that did not answer your question.
