### ISSUE TITLE
DWURecyclingAlert Red alert while rendering images and cells...

### ISSUE THREAD

**Issue by ezrover** [linkedin/LayoutKit#63]
FeedTableView in sample app with the following FeedItemLayout causes red boxes around images as well as high latency alert from DWURecyclingAlert. Any thoughts on how I can optimize image loading and layout?

https://github.com/diwu/DWURecyclingAlert/blob/master/RecyclingAlert/DWURecyclingAlert/DWURecyclingAlert.m

`        let actorCommentLayout = StackLayout(axis: .horizontal, sublayouts: [
            SizeLayout<UIImageView>(width: 50, height: 50, config: { imageView in

```
            imageView.image = UIImage(named: "Avatar\(imageIndex.instance.value)")
        }),
        LabelLayout(text: actorComment, alignment: .centerLeading)
    ])`
```

![simulator screen shot oct 29 2016 1 00 44 pm](https://cloud.githubusercontent.com/assets/1473932/19832420/340323f6-9dd8-11e6-9dbc-e163afa3e063.png)

**Comment by nicksnyder** [comment]
Thanks for reporting!

I am not familiar with DWURecyclingAlert but based on the README it triggers for two reasons:
> Displays non-recycled UIView, CALayer and UIImage objects with bold red bolders.
> Displays the time it takes to complete each time sensitive API calls, in milliseconds.

LayoutKit does not reuse views by default so my *guess* is that is causing the alert (and not necessarily that it is slow). 8ms doesn't seem that bad since the README also says this:

> Your code usually has less than ten milliseconds to run before it causes a frame drop.

What hardware did you test on?

LayoutKit will reuse views if a layout has a `viewReuseId`. For the feed example, you can try adding `viewReuseId` parameters to all of the `LabelLayout`s and `SizeLayout<UIImageView>`s in [ProfileCardLayout](https://github.com/linkedin/LayoutKit/blob/master/LayoutKitExampleLayouts/ProfileCardLayout.swift), [FeedItemLayout](https://github.com/linkedin/LayoutKit/blob/master/LayoutKitExampleLayouts/FeedItemLayout.swift), and [ContentLayout](https://github.com/linkedin/LayoutKit/blob/master/LayoutKitExampleLayouts/FeedItemLayout.swift#L69) to see (1) if that gets rid of the warning and more importantly (2) if it actually improves performance.

If it does improve performance, feel free to submit a PR to make those changes to the example layouts (they were created before `viewReuseId` existed).

Collecting this data would also help inform how beneficial #58 would be.

**Comment by nicksnyder** [comment]
I experimented with `viewReuseId` and it does noticeably improve performance.

#63 updates the example layouts.

**Comment by ezrover** [comment]
Excellent, Thank you Nick.

Cheers,
Nader Rahimizad

**Comment by nicksnyder** [comment]
For clarification, if/when #58 is resolved it may not be necessary to specify viewReuseIds everywhere to get better performance (it would only be necessary for animations).
