### ISSUE TITLE
"Not the most performant way to do a corner radius"

### ISSUE THREAD

**Issue by AndrewBarba** [linkedin/LayoutKit#78]
Hey guys, found out about LayoutKit from Realm today, looks incredible. We've been having serious issues with auto layout performance and also use a lot of corner radius's in our views, can you provide a link to something more performant?

Re: [http://layoutkit.org/building-ui/#defining-composite-layouts](http://layoutkit.org/building-ui/#defining-composite-layouts)

**Comment by Jauzee** [comment]
@AndrewBarba more effective way to round an `UIView`is to assign an `CAShapeLayer`with desired `UIBezierPath`. Something like this:

```swift
let radius: CGFloat = 5
let path = UIBezierPath(roundedRect: bounds, byRoundingCorners: corners, cornerRadii: CGSize(width: radius, height: radius))
let mask = CAShapeLayer()
mask.path = path.cgPath
self.layer.mask = mask
```

**Comment by nicksnyder** [comment]
> We've been having serious issues with auto layout performance and also use a lot of corner radius's in our views

Make sure you measure perf using instruments so you know what the actual performance problem is. For example, if you disable all occurrences of corner radius in your cells, does FPS go up during scroll? If yes, then it is worth fixing; if no, then don't bother.

> can you provide a link to something more performant

The two general solutions that I am aware of are:
1. Masking, like what @Jauzee suggested
2. Processing the image so that it is actually a circle (transparent corners). Processing could be done on the server or on the client depending on your requirements.

Hope that helps.

**Comment by AndrewBarba** [comment]
@Jauzee @nicksnyder Thank you guys, all great tips
